
import './pages/css/menu.css';
import './pages/css/pagina.css';
import Image from 'next/image';


import Link from 'next/link';

export const metadata = {
  title: 'FacturApp',
  description: 'Generated by Next.js',
}
export default function RootLayout({ children }) {
 return (
    <html lang="es">
      <body>
        {children}
        </body>
    </html>
  )
}
